adventure/urls.py
from django.urls import include, path, re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recommender/', include('recommender.urls')),
    path('mapper/', include('mapper.urls')),
    path('', include('authentication.urls')),
    path('profile/', include('userprofile.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
]

mapper/urls.py
from django.urls import path
from mapper import views

app_name = 'mapper'

urlpatterns = [
    path('', views.index, name='index'),
    path('previous', views.previous, name='previous'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.index, name='index'),
    path('location/', views.update_location, name='location_async'),
    path('delete/', views.delete_recommendation, name='delete_recommendation'),
]

authentication/models.py
from django.db import models
from django.contrib.gis.db import models as gis_models
from django.contrib.auth.models import AbstractUser
from django.contrib.gis.geos import Point

    
class User(AbstractUser):
    recommendations = models.ManyToManyField('Recommendation', blank=True)
    location = gis_models.PointField(default=Point(0.0, 0.0))
    old_recommendations = models.ManyToManyField('Recommendation', blank=True, related_name='old_recommendations')

class Recommendation(gis_models.Model):
    id = gis_models.BigAutoField(primary_key=True)
    description = models.CharField(max_length=500)
    location = gis_models.PointField()
    link = models.CharField(max_length=5000, blank=True)

authentication/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import  HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import User


def login_view(request):
    if request.user.is_authenticated:
        return redirect('recommender/')
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return redirect('recommender/')
        else:
            return render(request, "authentication/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "authentication/login.html")


def logout_view(request):
    logout(request)
    return redirect('login')


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "authentication/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
        # hadeling if a user already exists
            return render(request, "authentication/register.html", {
                "message": "Username already taken."
            })
        except ValueError:
        # handling if the user didnt fill in all the fields
            return render(request, "authentication/register.html", {
                "message": "Please fill all required fields."
            })

        login(request, user)
        return redirect('recommender/')
    else:
        return render(request, "authentication/register.html")

authentication/templates/authentication/authlayout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>MA - {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'authentication/style.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <meta content='maximum-scale=1.0, initial-scale=1.0, width=device-width' name='viewport'>
        <link rel="shortcut icon" type="image/jpg" href="{% static 'authentication/smol.png' %}"/>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@400;600;700&display=swap');
        
            * {
                font-family: 'Red Hat Display', sans-serif !important;
            }
            a{
                color:inherit;
                text-decoration:none;
            }
            a:hover{
                color:inherit;
                opacity:0.7;
                text-decoration:none;
                pointer-events: pointer;
            }
        {% block style %}
        {% endblock %}
        </style>
        
        <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        {% block script %}
        {% endblock %}
    </head>
    <body>

        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

authentication/templates/authentication/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>MA - {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <meta content='maximum-scale=1.0, initial-scale=1.0, width=device-width' name='viewport'>
        <link rel="shortcut icon" type="image/jpg" href="{% static 'authentication/smol.png' %}"/>
        <style>
        {% block style %}
        {% endblock %}
        </style>
        
        <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
        <link href="{% static 'authentication/style.css' %}" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        {% block script %}
        {% endblock %}
    </head>
    <body>
        <div id = "nav">

        
        <nav class="navbar navbar-expand-lg navbar-light m-2 shadow-lg rounded" id = "navbar">
            <div id = "nav-logo">
            <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'authentication/smol.png' %}" alt="logo" class="navbar-brand" width = "70px"></a>
            <h3><a  href="{% url 'index' %}">Mood</a></h3>
            </div>
          
            <div>
              <ul class="navbar-nav mt-3">
                
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mapper:index' %}">Map</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mapper:previous' %}">Previous</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <p class= 'text-capitalize nav-link'><a class = "btn btn-dark" href="{% url 'profile:index' %}"><i class="ri-user-line align-bottom" style = "color:white; padding-right:2px"></i>&nbsp<strong style = "padding-right:5px">{{ user.username }}</strong></a></p>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>

        </div>

        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

authentication/templates/authentication/login.html
{% extends "authentication/authlayout.html" %}
{% load static %}
{% block title %}Login{% endblock %}

{% block body %}
<section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        {%if message%}
        <div class="alert alert-danger">
            {{message}}
        </div>
    {%endif%}
        <div class="col-xl-10" >
          <div class="card rounded-3 text-black shadow-lg" style="border-radius: 15px;">
            <div class="row g-0 ">
              <div class="col-lg-6 " >
                <div class="card-body p-md-5 mx-md-4 " >
  
                  <div class="text-center">
                    <img src="{% static 'authentication/smol.png' %}"
                      style="width: 105px;" alt="logo">
                    <h4 class="mt-1 mb-5 pb-1">Login</h4>
                  </div>
  
                  <form action="{% url 'login' %}" method="post" >
                    {% csrf_token %}
  
                    <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example11">Username</label>
                      <input type="username" name="username" id="form2Example11" class="form-control"
                        placeholder="Username" />
                    </div>
  
                    <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example22">Password</label>
                      <input type="password" id="form2Example22" name="password" class="form-control" placeholder = "Password" />
                    </div>
  
                    <div class="text-center pt-1 mb-5 pb-1">
                      <button id = "loginbtn" class="btn btn-block fa-lg gradient-custom-2 mb-3" style = "color: white" value="Login" type="submit">Log
                        in</button>
                    </div>
  
                    <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2">Don't have an account?</p> 
                      &nbsp
                      <a href="{% url 'register' %}" class="btn btn-outline-danger">Create new</a>
                    </div>
  
                  </form>
  
                </div>
              </div> 
              <div class="col-lg-6 d-flex align-items-center" id = "loginbg">
                <div class="rounded" id = "loginbg1"></div>
                <div class="text-white px-3 py-4 p-md-4 mx-md-4" id = "text">
                  <h2 class="mb-4 text-dark">Mood Adventure</h2>
                  <p class=" mb-0 text-dark">A django web application made for Timathon.</p>
                  <p class=" mb-0 text-dark">Takes in your current mood and transportaion method, then uses selenium on the server side (very slow) to recommend a place for you to visit.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

authentication/templates/authentication/register.html
{% extends "authentication/authlayout.html" %}
{%load static%}
{% block title %}Register{% endblock %}

{% block body %}

<section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          {%if message%}
              <div class="alert alert-danger">
                  {{message}}
              </div>
          {%endif%}
        <div class="col-xl-10">
          <div class="card rounded-3 text-black shadow-lg" style="border-radius: 15px;">
            <div class="row g-0">
                
              <div class="col-lg-6">
                
                <div class="card-body p-md-5 mx-md-4">
  
                  <div class="text-center">
                    <img src="{% static 'authentication/smol.png' %}"
                      style="width: 105px;" alt="logo">
                    <h4 class="mt-1 mb-3 pb-1">Register</h4>
                  </div>
  
                  <form action="{% url 'register' %}" method="post" >
                    {% csrf_token %}
  
                    <div class="form-outline mb-3">
                        <label class="form-label" for="form2Example11">Username</label>
                      <input type="username" name="username" id="form2Example11" class="form-control"
                        placeholder="Username" />
                    </div>
                    
                    <div class="form-outline mb-3">
                        <label class="form-label" for="form2Example11">Email</label>
                      <input type="email" name="email" id="form2Example11" class="form-control"
                        placeholder="Email address" />
                    </div>

                    <div class="form-outline mb-3">
                        <label class="form-label" for="form2Example22">Password</label>
                      <input type="Password" id="form2Example22" name="password" class="form-control" placeholder = "Password" />
                    </div>

                    <div class="form-outline mb-3">
                        <label class="form-label" for="form2Example22">Confirm Password</label>
                      <input type="Password" id="form2Example22" name="confirmation" class="form-control" placeholder = "Password" />
                    </div>
  
                    <div class="text-center pt-1 mb-2 pb-1">
                      <button id = "loginbtn" class="btn btn-block fa-lg gradient-custom-2 mb-3" style = "color: white" value="Register" type="submit">Register</button>
                    </div>
  
                    <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2">Already have an account?</p> 
                      &nbsp
                      <a href="{% url 'login' %}" class="btn btn-outline-primary">Login</a>
                    </div>
  
                  </form>
  
                </div>
              </div>
              <div class="col-lg-6 d-flex align-items-center" id = "loginbg">
                <div class="rounded" id = "loginbg1"></div>
                <div class="text-white px-3 py-4 p-md-4 mx-md-4" id = "text">
                  <h2 class="mb-4 text-dark">Mood Adventure</h2>
                  <p class=" mb-0 text-dark">A django web application made for Timathon.</p>
                  <p class=" mb-0 text-dark">Takes in your current mood and transportaion method, then uses selenium on the server side (very slow) to recommend a place for you to visit.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}