adventure/urls.py
from django.urls import include, path, re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recommender/', include('recommender.urls')),
    path('mapper/', include('mapper.urls')),
    path('', include('authentication.urls')),
    path('profile/', include('userprofile.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mapper/urls.py
from django.urls import path
from mapper import views

app_name = 'mapper'

urlpatterns = [
    path('', views.index, name='index'),
    path('previous', views.previous, name='previous'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.index, name='index'),
    path('location/', views.update_location, name='location_async'),
    path('delete/', views.delete_recommendation, name='delete_recommendation'),
]

userprofile/models.py
from django.db import models

# Create your models here.

userprofile/views.py
import json
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.contrib.gis.db.models.functions import Distance
from django.contrib.gis.geos import Point

# getting user's location and recommendations
def index(request):
    if not request.user.is_authenticated:
        return redirect('login')
    lat = request.user.location.y
    long = request.user.location.x
    user_location = request.user.location
    queryset = request.user.old_recommendations.annotate(distance=Distance('location',user_location)).order_by('distance')[0:6]
    return render(request, 'userprofile/index.html' , context={'long': long, 'lat': lat, 'recommendations': queryset})

# update user's location
def update_location(request):
    # check if user is authenticated
    if request.user.is_authenticated:
        # check if user is posting data
        if request.method == 'POST':
            # get the data from the request and decoding it
            body_unicode = request.body.decode('utf-8')
            body = json.loads(body_unicode)

            long = body['long']
            lat = body['lat']

            # make a new point with the user's new location
            point = Point(float(long), float(lat))

            #update users location in database 
            request.user.location = point
            request.user.save()
            return JsonResponse({'status': 'success'})

# delete unwanted recommendations
def delete_recommendation(request):
    # check if user is authenticated
    if request.user.is_authenticated:
        # check if user is posting data
        if request.method == 'POST':
            # get the data from the request and decoding it to get the id of the unwanted recommendation
            body_unicode = request.body.decode('utf-8')
            body = json.loads(body_unicode)
            pk = body['pk']

            # delete the unwanted recommendation from the database
            recommendation = request.user.old_recommendations.get(pk=pk)
            recommendation.delete()
            return JsonResponse({'status': 'success'})

userprofile/templates/userprofile/index.html
{% extends "authentication/layout.html" %}

{% block title %}{{user.username}}'s Profile{% endblock %}

{% block body %}
<section style = "height: 80vh">
    <div class="container py-5 h-100 ">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card mb-5" style="border-radius: 15px;">
            <div class="card-body p-4 shadow" style="border-radius: 15px;">
              <h3 class="mb-3"><i class="ri-map-pin-user-line align-bottom"></i> Current Location</h3>
              <p class="small mb-0"><i class="ri-close-circle-line align-bottom"></i> <span class="mx-2">|</span> <span id = 'longdis'>Longitude: <strong>{{long}}</strong></span></p>
              <p class="small mb-0"><i class="ri-play-circle-line align-bottom"></i> <span class="mx-2">|</span> <span id = 'latdis'>Latitude: <strong>{{lat}}</strong></span></p>
              <hr class="my-4">
              <div class="d-flex justify-content-start align-items-center">
                <form action= "" method="post">
                    <input type="hidden" name="lat" id="lat" value="">
                    <input type="hidden" name="long" id="long" value="">
                    <a href="#!" id = "demo" class="btn btn-outline-primary btn-sm btn-floating" onclick="getLocation()">
                        Get Location
                    </a>
                    <button type="submit" class="btn btn-outline-dark btn-sm btn-floating" id = "submit">
                        Update Location
                    </button>
                </form>
              </div>
            </div>
          </div>
          <div class="card shadow mb-5" style="border-radius: 15px;">
            <div class="card-body p-4">
              <h3 class="mb-5">Previous Recommendations</h3>
            {% if recommendations %}
                {% for rec in recommendations %}
                    <span >
                        <h4 class=" mb-0 mt-3"><a class = "link" href = "{{rec.link}}" target = "_blank">{{ rec.description }}</a> </h4>
                        <div id = "parent{{rec.id}}" class="d-flex justify-content-start align-items-center" style = "justify-content: space-between !important">
                            <p class="mt-3"><small class="text-muted">{{rec.distance.m|floatformat:"0"}}m away from you</small></p>
                            
                            <button type="button" name = {{rec.id}} id = "delbtn{{rec.id}}" class="btn btn-outline-dark btn-sm btn-floating float-right">
                                Delete
                            </button>
                        </div>
                        <hr class="my-4">
                    </span>
                {% endfor %}
            {%else%}
                <p class="text-center">No recommendations yet</p>
            {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  {% if recommendations %}
            <img src="/media/mountainbg.png" alt="map" id = 'mountains'>
            <img src="/media/tree6.png" alt="map" id = 'tree6'>
        {% else %}
            <img src="/media/mountainbg.png" alt="map" id = 'mountains'>
            <img src="/media/tree2.png" alt="map" id = 'tree2'>
        {%endif%}

  <script>

    // getting all the elements needed
    var x = document.getElementById("demo");
    const lat = document.getElementById("lat");
    const long = document.getElementById("long");
    const latdis = document.getElementById("latdis");
    const longdis = document.getElementById("longdis");

    // get the location of the user
    function getLocation() {
        
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
      } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
      }
    }
    
    // setting the location of the user as the value of hidden inputs in the form
    function showPosition(position) {
      lat.value=position.coords.latitude ;
      long.value =position.coords.longitude;
    }

    // on submit, send the location to the server
    document.getElementById("submit").addEventListener("click", function(event){

        // prevent page refresh on form submit
        event.preventDefault();

        // contacting the server and sending the new location of the user
        fetch ("{% url 'profile:location_async' %}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: JSON.stringify({
                'lat': lat.value,
                'long': long.value
            })
        }).then(function(response){
            return response.json();
        }).then(function(data){
            //console.log(data);

            // if the location is updated, show the new location on the page
            if (data.status === 'success'){
                latdis.innerHTML = "Latitude: <strong>" + lat.value+"</strong>";
                longdis.innerHTML = "Longitude: <strong>" + long.value+"</strong>";
                console.log('success :)');
            }
        });
    });

    // check if the user has any recommendations
    {% if recommendations %}

        // if the user has recommendations, add event listeners to the delete buttons
        {% for rec in recommendations %}

            let delbtn{{rec.id}} = document.getElementById("delbtn{{rec.id}}");

            delbtn{{rec.id}}.addEventListener("click", function(event){

                // prevent form from submitting
                event.preventDefault();

                // deleting the specific recommendation from the database
                fetch ("{% url 'profile:delete_recommendation' %}", {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify({
                        'pk': '{{rec.id}}'
                    })
                })

                .then(function(response){
                    return response.json();
                })
                
                .then(function(data){
                    console.log(data);
                    if (data.status === 'success'){
                        // if the recommendation is deleted, remove the recommendation from the page
                        console.log('success :)');
                        //delbtn{{rec.id}}.parentNode.remove();
                        document.getElementById("parent{{rec.id}}").parentNode.remove();
                    }
                });
            });
        {% endfor %}
    {% endif %}
  </script>
{% endblock %}